version: "3"
services:
  mysql-auth:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - ./auth/ops/db/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: auth_user
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_pwd
    ports:
      - "3306:3306"
    container_name: auth_mysql
    network_mode: "bridge"
  mysql-feedbacks:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - ./feedbacks/ops/db/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: feedbacks_user
      MYSQL_DATABASE: feedbacks_db
      MYSQL_USER: feedbacks_user
      MYSQL_PASSWORD: feedbacks_pwd
    ports:
      - "3307:3306"
    container_name: feedbacks_mysql
    network_mode: "bridge"
  mysql-votes:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - ./votes/ops/db/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: votes_user
      MYSQL_DATABASE: votes_db
      MYSQL_USER: votes_user
      MYSQL_PASSWORD: votes_pwd
    ports:
      - "3308:3306"
    container_name: votes_mysql
    network_mode: "bridge"
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
#    container_name: clean-architecture-go-v2-grafana
#    network_mode: "bridge"
#    depends_on:
#      - prometheus
#      - prometheus-pushgateway
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - 9090:9090
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#    volumes:
#      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
#    container_name: clean-architecture-go-v2-prometheus
#    network_mode: "bridge"
#  prometheus-pushgateway:
#    image: prom/pushgateway
#    container_name: clean-architecture-go-v2-pushgateway
#    expose:
#      - 9091
#    ports:
#      - "9091:9091"
